config/routes.rb
Rails.application.routes.draw do
  resources :sample_articles
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/sample_article.rb
class SampleArticle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sample_articles_controller.rb
class SampleArticlesController < ApplicationController
  before_action :set_sample_article, only: %i[ show edit update destroy ]

  # GET /sample_articles or /sample_articles.json
  def index
    @sample_articles = SampleArticle.all
  end

  # GET /sample_articles/1 or /sample_articles/1.json
  def show
  end

  # GET /sample_articles/new
  def new
    @sample_article = SampleArticle.new
  end

  # GET /sample_articles/1/edit
  def edit
  end

  # POST /sample_articles or /sample_articles.json
  def create
    @sample_article = SampleArticle.new(sample_article_params)

    respond_to do |format|
      if @sample_article.save
        format.html { redirect_to sample_article_url(@sample_article), notice: "Sample article was successfully created." }
        format.json { render :show, status: :created, location: @sample_article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sample_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sample_articles/1 or /sample_articles/1.json
  def update
    respond_to do |format|
      if @sample_article.update(sample_article_params)
        format.html { redirect_to sample_article_url(@sample_article), notice: "Sample article was successfully updated." }
        format.json { render :show, status: :ok, location: @sample_article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sample_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sample_articles/1 or /sample_articles/1.json
  def destroy
    @sample_article.destroy

    respond_to do |format|
      format.html { redirect_to sample_articles_url, notice: "Sample article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample_article
      @sample_article = SampleArticle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sample_article_params
      params.require(:sample_article).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WonderfulPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sample_articles/_form.html.erb
<%= form_with(model: sample_article, local: true) do |form| %>
  <% if sample_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample_article.errors.count, "error") %> prohibited this sample_article from being saved:</h2>

      <ul>
        <% sample_article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sample_articles/edit.html.erb
<h1>Editing Sample Article</h1>

<%= render 'form', sample_article: @sample_article %>

<%= link_to 'Show', @sample_article %> |
<%= link_to 'Back', sample_articles_path %>

app/views/sample_articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sample Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sample_articles.each do |sample_article| %>
      <tr>
        <td><%= sample_article.title %></td>
        <td><%= sample_article.content %></td>
        <td><%= link_to 'Show', sample_article %></td>
        <td><%= link_to 'Edit', edit_sample_article_path(sample_article) %></td>
        <td><%= link_to 'Destroy', sample_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample Article', new_sample_article_path %>

app/views/sample_articles/new.html.erb
<h1>New Sample Article</h1>

<%= render 'form', sample_article: @sample_article %>

<%= link_to 'Back', sample_articles_path %>

app/views/sample_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sample_article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @sample_article.content %>
</p>

<%= link_to 'Edit', edit_sample_article_path(@sample_article) %> |
<%= link_to 'Back', sample_articles_path %>